# .goreleaser.yml
# Build customization
version: 2 # Specify config format version
project_name: goflat

# Explicitly skip building binaries for the library
builds:
  - skip: true

checksum:
  name_template: 'checksums.txt'
# snapshot:
#   name_template: "{{ incpatch .Version }}-next" # Removed deprecated field
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Release configuration (GitHub Releases)
release:
  github:
    owner: sanjibdevnathlabs
    name: goflat
  # Optional: Draft releases are recommended
  draft: false
  # Optional: Prerelease automatically if the tag is not a stable release
  # prerelease: auto
  # Optional: Name template for the release title
  # name_template: "{{.ProjectName}}-{{.Tag}}"

# Archiving source code
archives:
  - id: source # Optional ID
    format: tar.gz
    # Optional: Archive name template (defaults work well for source)
    # name_template: '{{ .ProjectName }}_{{ .Version }}_source'
    files:
      - LICENSE
      - README.md
      - go.mod
      - go.sum
      - '*.go' # Include go source files
      - '.github/**' # Include relevant github configs

# Optional: nfpm configuration for Linux packages (deb, rpm)
# nfpm:
#   formats:
#     - deb
#     - rpm
#   vendor: Your Name
#   homepage: https://github.com/sanjibdevnathlabs/goflat
#   maintainer: Your Name <your-email@example.com>
#   description: Flatten/unflatten nested map or JSON object in Golang.
#   license: MIT
#   bindir: /usr/bin
