# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

permissions:
  contents: write # Needed to create releases and upload assets
  # Optional: If using id-token for publishing elsewhere (e.g., OIDC)
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changelog generation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0' # Or use a specific version goreleaser should use

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # Optional: specify the goreleaser version to use (e.g., v1.2.3 or latest)
          version: latest
          args: release --clean
        env:
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
