name: build
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        # Test on Go 1.23 and latest stable Go version
        go: ['1.23.0', 'stable']

    name: Test (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    # Allow the stable Go build to fail without failing the entire workflow
    continue-on-error: ${{ matrix.go == 'stable' }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

    - name: Test & Coverage
      run: |
        go test -race -coverprofile=coverage.out -covermode=atomic ./...

    # Step to upload coverage report to Codecov
    # To enable:
    # 1. Sign up at https://about.codecov.io/
    # 2. Add the CODECOV_TOKEN secret to your GitHub repository settings
    # 3. Uncomment the following lines:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ${{ github.repository }}

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: govulncheck ./...
